<?php foreach ($users as $key => $user) : ?>
    <h4>Пользователь № <?= htmlspecialchars($key) ?> : <?= htmlspecialchars($user['nickname']) ?> </h4>
<?php endforeach ?>

<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>

<?php if (empty($resultUsers)) : ?>
    <h3> Такого пользователя нет или поле для поиска пустое! </h3>
<?php endif; ?>


<?php foreach ($resultUsers as $user) : ?>
    <?= htmlspecialchars($user) ?>
<?php endforeach ?>