<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php if ($loginUser) : ?>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <div>
            <div><?= 'Welcome to Slim, ' . $loginUser['name'] . '!' ?></div>
        </div>
        <input type="submit" value="Sign Out">
    </form>
<?php else : ?>
    <form action="/session" method="post">
        <div>
            <label>
                Имя
                <input type="text" name="user[name]">
            </label>
        </div>
        <div>
            <label>
                Почта
                <input type="email" name="user[email]">
            </label>
        </div>
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>